<template>
  <BaseGlass class="mx-20 mt-20 mb-12 p-8 space-y-2">
    <h1>Hello World, 初めまして</h1>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi exercitationem omnis voluptatibus minus tenetur cupiditate, rem nam tempore dignissimos a sunt, facere quam obcaecati. Nihil veritatis hic doloremque laborum quam.</p>
  </BaseGlass>
</template>
